#index:
#    path: /
#    controller: App\Controller\DefaultController::index
route_accueil:
    path: /accueil
    controller: App\Controller\AdherentController::index

liste-adherent:
    path: /liste-adherent
    controller: App\Controller\AdherentController::listerAdherent
