#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\AdherentController::index

liste-adherent:
    path: /liste-adherent
    controller: App\Controller\AdherentController::listerAdherent

adherent-consulter:
    path: /adherent/consulter/{adherent_id}
    controller: App\Controller\AdherentController::consulterAdherent

adherent-ajouter:
    path: /adherent-ajouter
    controller: App\Controller\AdherentController::ajouterAdherent

liste-activites:
    path: /liste-activites
    controller: App\Controller\ActivitesController::listerActivites

activites-consulter:
    path: /activites/consulter/{activites_id}
    controller: App\Controller\ActivitesController::consulterActivites

activites-ajouter:
    path: /activites-ajouter
    controller: App\Controller\ActivitesController::ajouterActivites

horaire-ajouter:
    path: /horaire-ajouter
    controller: App\Controller\ActivitesController::ajouterHoraire

reglages:
    path: /reglages
    controller: App\Controller\AdminController::listerReglages

paiement-consulter:
    path: /paiement/consulter/{paiement_id}
    controller: App\Controller\AdminController::consulterPaiement

paiement-ajouter:
    path: /paiement-ajouter
    controller: App\Controller\AdminController::ajouterPaiement

paiement-modifier:
    path: /paiement-modifier/{paiement_id}
    controller: App\Controller\AdminController::modifierPaiement

annee-consulter:
    path: /annee/consulter/{annee_id}
    controller: App\Controller\AdminController::consulterAnnee

annee-ajouter:
    path: /annee-ajouter
    controller: App\Controller\AdminController::ajouterAnnee

annee-modifier:
    path: /annee-modifier/{annee_id}
    controller: App\Controller\AdminController::modifierAnnee

adhesion-ajouter:
    path: /adhesion-ajouter
    controller: App\Controller\AdherentController::ajouterAdhesion

responsable-ajouter:
    path: /responsable-ajouter
    controller: App\Controller\AdherentController::ajouterResponsable

famille-ajouter:
    path: /famille-ajouter
    controller: App\Controller\AdherentController::ajouterFamille