#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\AdherentController::index

liste-adherent:
    path: /liste-adherent
    controller: App\Controller\AdherentController::listerAdherent

adherent-consulter:
    path: /adherent/consulter/{adherent_id}
    controller: App\Controller\AdherentController::consulterAdherent

liste-activites:
    path: /liste-activites
    controller: App\Controller\ActivitesController::listerActivites

activites-consulter:
    path: /activites/consulter/{activites_id}
    controller: App\Controller\ActivitesController::consulterActivites