#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\AdherentController::index

liste-adherent:
    path: /liste-adherent
    controller: App\Controller\AdherentController::listerAdherent

adherent-consulter:
    path: /adherent/consulter/{adherent_id}
    controller: App\Controller\AdherentController::consulterAdherent

adherent-ajouter:
    path: /adherent-ajouter
    controller: App\Controller\AdherentController::ajouterAdherent

liste-activites:
    path: /liste-activites
    controller: App\Controller\ActivitesController::listerActivites

activites-consulter:
    path: /activites/consulter/{activites_id}
    controller: App\Controller\ActivitesController::consulterActivites

reglages:
    path: /reglages
    controller: App\Controller\AdminController::listerReglages

paiement-consulter:
    path: /paiement/consulter/{paiement_id}
    controller: App\Controller\AdminController::consulterPaiment

annee-consulter:
    path: /annee/consulter/{annee_id}
    controller: App\Controller\AdminController::consulterPaiment

adhesion-ajouter:
    path: /adhesion-ajouter
    controller: App\Controller\AdherentController::ajouterAdhesion

responsable-ajouter:
    path: /responsable-ajouter
    controller: App\Controller\AdherentController::ajouterResponsable