#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\AdherentController::index




liste-adherent:
    path: /liste-adherent
    controller: App\Controller\AdherentController::listerAdherent

adherent-consulter:
    path: /adherent/consulter/{adherent_id}
    controller: App\Controller\AdherentController::consulterAdherent

adherent-ajouter:
    path: /adherent-ajouter
    controller: App\Controller\AdherentController::ajouterAdherent

adherent-modifier:
    path: /adherent-modifier/{adherent_id}
    controller: App\Controller\AdherentController::modifierAdherent

adherent-supprimer:
    path: /adherent-supprimer/{adherent_id}
    controller: App\Controller\AdherentController::supprimerAdherent




liste-activites:
    path: /liste-activites
    controller: App\Controller\ActivitesController::listerActivites

activites-consulter:
    path: /activites/consulter/{activites_id}
    controller: App\Controller\ActivitesController::consulterActivites

activites-ajouter:
    path: /activites-ajouter
    controller: App\Controller\ActivitesController::ajouterActivites

activites-modifier:
    path: /activites-modifier/{activites_id}
    controller: App\Controller\ActivitesController::modifierActivites

activites-supprimer:
    path: /activites-supprimer/{activites_id}
    controller: App\Controller\ActivitesController::supprimerActivites




horaire-ajouter:
    path: /horaire-ajouter
    controller: App\Controller\ActivitesController::ajouterHoraire

horaire-modifier:
    path: /horaire-modifier/{horaire_id}
    controller: App\Controller\ActivitesController::modifierHoraire

horaire-supprimer:
    path: /horaire-supprimer/{horaire_id}
    controller: App\Controller\ActivitesController::supprimerHoraire




reglages:
    path: /reglages
    controller: App\Controller\AdminController::listerReglages

paiement-consulter:
    path: /paiement/consulter/{paiement_id}
    controller: App\Controller\AdminController::consulterPaiement

paiement-ajouter:
    path: /paiement-ajouter
    controller: App\Controller\AdminController::ajouterPaiement

paiement-modifier:
    path: /paiement-modifier/{paiement_id}
    controller: App\Controller\AdminController::modifierPaiement

paiement-supprimer:
    path: /paiement-supprimer/{paiement_id}
    controller: App\Controller\AdminController::supprimerPaiement

annee-consulter:
    path: /annee/consulter/{annee_id}
    controller: App\Controller\AdminController::consulterAnnee

annee-ajouter:
    path: /annee-ajouter
    controller: App\Controller\AdminController::ajouterAnnee

annee-modifier:
    path: /annee-modifier/{annee_id}
    controller: App\Controller\AdminController::modifierAnnee

annee-supprimer:
    path: /annee-supprimer/{annee_id}
    controller: App\Controller\AdminController::supprimerAnnee




adhesion-ajouter:
    path: /adhesion-ajouter
    controller: App\Controller\AdherentController::ajouterAdhesion

adhesion-modifier:
    path: /adhesion-modifier/{adhesion_id}
    controller: App\Controller\AdherentController::modifierAdhesion




responsable-consulter:
    path: /responsable-consulter/{responsable_id}
    controller: App\Controller\AdherentController::consulterResponsable

liste-responsable:
    path: /liste-responsable
    controller: App\Controller\AdherentController::listerResponsable

responsable-ajouter:
    path: /responsable-ajouter
    controller: App\Controller\AdherentController::ajouterResponsable

responsable-modifier:
    path: /responsable-modifier/{responsable_id}
    controller: App\Controller\AdherentController::modifierResponsable

responsable-supprimer:
    path: /responsable-supprimer/{responsable_id}
    controller: App\Controller\AdherentController::supprimerResponsable




famille-ajouter:
    path: /famille-ajouter
    controller: App\Controller\AdherentController::ajouterFamille